model_size: "125M"
hidden_size: 768
num_attention_heads: 12
num_layers: 12
ffn_hidden_size: 3072
dropout: 0.1
vocab_size: 50257
max_position_embeddings: 1024
learning_rate: 1e-4
weight_decay: 0.1
warmup_steps: 1000
scheduler: "linear"
optimizer: "adamw"
epochs: 5