model_size: "13B"
hidden_size: 5120
num_attention_heads: 40
num_layers: 40
ffn_hidden_size: 20480
dropout: 0.1
vocab_size: 50257
max_position_embeddings: 1024
learning_rate: 1e-4
weight_decay: 0.1
warmup_steps: 1000
scheduler: "linear"