model_size: "175B"
hidden_size: 12288
num_attention_heads: 96
num_layers: 96
ffn_hidden_size: 49152
dropout: 0.1
vocab_size: 50257
max_position_embeddings: 1024
learning_rate: 1e-4
weight_decay: 0.1
warmup_steps: 1000
scheduler: "linear"