model_size: "32M"
hidden_size: 384  # Further reduced hidden size
num_attention_heads: 6  # Fewer attention heads
num_layers: 8  # Reduced number of layers
ffn_hidden_size: 1536  # Feed-forward network hidden size (typically 4x hidden_size)
dropout: 0.1
vocab_size: 50257
max_position_embeddings: 1024
learning_rate: 1e-4
weight_decay: 0.1
warmup_steps: 1000
scheduler: "linear"
optimizer: "adamw"
epochs: 5
embedding_dim: 384  # Adjust embedding dim to match hidden size