model_size: "350M"
hidden_size: 1024
num_attention_heads: 16
num_layers: 24
ffn_hidden_size: 4096
dropout: 0.1
vocab_size: 50257
max_position_embeddings: 1024
learning_rate: 1e-4
weight_decay: 0.1
warmup_steps: 1000
scheduler: "linear"